ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS season_number INTEGER NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS old_age SMALLINT NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS new_age SMALLINT NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS old_price BIGINT NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS new_price BIGINT NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS growth_applied SMALLINT NULL;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS goals INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS assists INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS overall_history
ADD COLUMN IF NOT EXISTS updated_by_admin_id INTEGER NULL;

CREATE INDEX IF NOT EXISTS idx_overall_history_season_number ON overall_history(season_number);

